version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: andrii
      POSTGRES_PASSWORD: 2024
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
